package com.documania.backend.role;

public enum PermissionCode {
    DASHBOARD_READ,

    CLIENT_READ,
    CLIENT_CREATE,
    CLIENT_UPDATE,
    CLIENT_ARCHIVE,
    CLIENT_RESTORE,

    SERVICE_READ,
    SERVICE_CREATE,
    SERVICE_UPDATE,
    SERVICE_ARCHIVE,
    SERVICE_RESTORE,

    OFFER_READ,
    OFFER_CREATE,
    OFFER_UPDATE,
    OFFER_ARCHIVE,
    OFFER_RESTORE,

    ORDER_READ,

    SUBSCRIPTION_READ,

    ARCHIVE_READ,
    AUDIT_READ,

    TICKET_READ,
    TICKET_UPDATE,

    CLIENT_EXPORT,
    ORDER_EXPORT,
    SUBSCRIPTION_EXPORT
}